---
company_name: mycompany
apps:
  -
    name: ap-lms1d-1
    script_source: local
    start_script_path: /apps/serviceaccount/domain/ap_lsmls_1/apachectl
    stop_script_path: /apps/serviceaccount/domain/ap_lsmls_1/apachectl
    validate_script_path: /apps/serviceaccount/domain/ap_lsmls_1/apachectl
  - 
    name: ap-lms1d-2
    script_source: https://github.com/ymadem/app_s
    start_script_path: scripts/start.sh
    stop_script_path: scripts/stop.sh
    validate_script_path: scripts/validate.sh
  - 
    name: ap-lms1d-3
    script_source: https://github.com/ymadem/app_s
    start_script_path: scripts/start.sh
    stop_script_path: scripts/stop.sh
    validate_script_path: scripts/validate.sh