---
- name: Check if a reboot is required
  shell: needs-restarting -r
  register: reboot_check
  ignore_errors: true

- name: Print reboot required status
  debug:
    msg: "Reboot is required: {{ reboot_check.rc == 1 }}"

- name: Fail if reboot is required
  fail:
    msg: "Reboot is required on this host."
  when: reboot_check.rc == 1
