---
- name: Check if the app start script exists
  shell: |
    [ -f "/etc/{{ company_name }}/{{ item.name }}/{{ item.start_script_path | basename }}" ]
  with_items: "{{ apps }}"
  register: start_script_status

- name: executing start scripts
  debug:
    msg: "echo app service starting"
  when: start_script_status.results

- name: executing start scripts
  shell: "/etc/{{ company_name }}/{{ item.name }}/{{ item.start_script_path | basename }}"
  with_items: "{{ apps }}"
  when: start_script_status.results
