---
- name: Check if the app start script exists
  stat:
    path: "/etc/{{ company_name }}/{{ item.name }}/{{ item.start_script_path | basename }}"
  register: script_stat

- name: Execute app start script if it exists
  shell: "/etc/{{ company_name }}/{{ item.name }}/{{ item.start_script_path | basename }}"
  when: script_stat.stat.exists
  become: true
