---
- name: Check if the app start script exists
  stat:
    path: "/etc/{{ company_name }}/{{ item.name }}/{{ item.start_script_path | basename }}"
  with_items: "{{ apps }}"
  register: start_script_stat

- name: Execute app start script if it exists
  shell: "/etc/{{ company_name }}/{{ item.name }}/{{ item.start_script_path | basename }}"
  with_items: "{{ apps }}"
  when: start_script_stat.stat.exists
  become: true
