---
- name: Check if the app start script exists
  shell: |
    [ -f "/etc/{{ company_name }}/{{ item.name }}/{{ item.start_script_path | basename }}" ]
  with_items: "{{ apps }}"
  register: start_script_status

- name: Executing stop scripts
  shell: "/etc/{{ company_name }}/{{ item.name }}/{{ item.start_script_path | basename }}"
  with_items: "{{ apps }}"
  when: stop_script_status.results
  register: cmd_start_output

- name: Start script execute results
  debug:
    msg: "{{ item.stdout_lines }}"
  with_items: "{{ cmd_start_output.results }}"
