---
- name: Check if the app stop script exists
  stat:
    path: "/etc/{{ company_name }}/{{ item.name }}/{{ item.stop_script_path | basename }}"
  with_items: "{{ apps }}"
  register: stop_script_stat

- name: Execute app stop script if it exists
  shell: "/etc/{{ company_name }}/{{ item.name }}/{{ item.stop_script_path | basename }}"
  with_items: "{{ apps }}"
  when: stop_script_stat.stat.exists
  become: true
