---
- name: Check if the app stop script exists
  shell: |
    [ -f "/etc/{{ company_name }}/{{ item.name }}/{{ item.stop_script_path | basename }}" ]
  with_items: "{{ apps }}"
  register: stop_script_status

- name: executing stop scripts
  debug:
    msg: "echo app service stopping"
  when: stop_script_status.results

- name: executing stop scripts
  shell: "/etc/{{ company_name }}/{{ item.name }}/{{ item.stop_script_path | basename }}"
  with_items: "{{ apps }}"
  when: stop_script_status.results


