---
- name: Check if the app stop script exists
  shell: |
    [ -f "/etc/{{ company_name }}/{{ item.name }}/{{ item.stop_script_path | basename }}" ]
  with_items: "{{ apps }}"
  register: stop_script_status

- name: Executing stop scripts
  shell: "/etc/{{ company_name }}/{{ item.name }}/{{ item.stop_script_path | basename }}"
  with_items: "{{ apps }}"
  when: stop_script_status.results
  register: cmd_stop_output

- name: Stop script execute results
  debug:
    msg: "{{ item.stdout_lines }}"
  with_items: "{{ cmd_stop_output.results }}"
