---
- name: Execute shutdown and startup script using Ansible
  hosts: all
  become: yes

  tasks:
    - name: Gather service facts
      ansible.builtin.service_facts:

    - name: Ensure the directory exists
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        mode: '0755'
      loop:
        - /{{ ansible_user }}/temp
        - /{{ ansible_user }}/cibc/{{ appname }}
  
    - name: Clone the repository
      ansible.builtin.git:
        repo: 'https://github.com/ymadem/patching'
        dest: /{{ ansible_user }}/temp
        version: main
        update: yes

    - name: Copy shutdown and startup scripts to destination directory
      copy: 
        src: "{{ item.src }}" 
        dest: "{{ item.dest }}"
      loop:
        - src: /{{ ansible_user }}/temp/ansible/apps/{{ appname }}/{{ appname }}_shutdown.sh
          dest: /{{ ansible_user }}/cibc/
        - src: /{{ ansible_user }}/temp/ansible/apps/{{ appname }}/{{ appname }}_startup.sh
          dest: /{{ ansible_user }}/cibc/
      
    - name: Set executable permissions for multiple files
      ansible.builtin.file:
        path: "{{ item }}"
        mode: '0755'
      loop:
        - /{{ ansible_user }}/cibc/{{ appname }}_shutdown.sh
        - /{{ ansible_user }}/cibc/{{ appname }}_startup.sh

    - name: Execute the shudown script
      ansible.builtin.shell: /{{ ansible_user }}/cibc/{{ appname }}_shutdown.sh

    - name: Debug the status of httpd service
      ansible.builtin.debug:
        msg: |
          httpd service status:
          - Active: {{ ansible_facts.services['httpd.service'].state }}
          - Enabled: {{ ansible_facts.services['httpd.service'].enabled }}
      when: "'httpd.service' in ansible_facts.services"