# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  # Define the first CentOS box
  config.vm.define "centos1" do |centos1|
    centos1.vm.box = "centos/7"
    centos1.vm.hostname = "app1.local.com"
    centos1.vm.network "private_network", ip: "192.168.33.10"
  end

  # Define the second CentOS box
  config.vm.define "centos2" do |centos2|
    centos2.vm.box = "centos/7"
    centos2.vm.hostname = "app2.local.com"
    centos2.vm.network "private_network", ip: "192.168.33.11"
  end

  # Define the third CentOS box
  config.vm.define "centos3" do |centos3|
    centos3.vm.box = "centos/7"
    centos3.vm.hostname = "db1.local.com"
    centos3.vm.network "private_network", ip: "192.168.33.12"
  end
  config.vm.provision "shell", path: "bootstrap.sh"
end
