---
- name: create temp directory
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
  loop:
    - /{{ ansible_user }}/temp/
    - /etc/{{ company_name }}/

- name: Ensure the directory exists
  ansible.builtin.file:
    path: "/etc/{{ company_name }}/{{ item.name }}"
    state: directory
    mode: '0755'
  with_items: "{{ apps }}"

- name: Clone the repository
  ansible.builtin.git:
    repo: '{{ item.script_source }}'
    dest: /{{ ansible_user }}/temp/{{ item.name }}
    version: main
    update: yes
  with_items: "{{ apps }}"
  when: item.script_source is regex('^http.*')

- name: Copy shutdown and startup scripts to destination directory
  ansible.builtin.copy:
    src: "/{{ ansible_user }}/temp/{{ item.name }}/{{ item.start_script_path }}"
    dest: "/etc/{{ company_name }}/{{ item.name }}/{{ item.start_script_path | basename }}"
    mode: '0755'
    remote_src: yes
  with_items: "{{ apps }}"