---
- name: create temp directory
  file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
  loop:
    - /{{ ansible_user }}/temp/
    - /etc/company/

- name: Ensure the directory exists
  file:
    path: "/etc/company/{{ item.name }}"
    state: directory
    mode: '0755'
  with_items: "{{ apps }}"

- name: Clone the repository
  ansible.builtin.git:
    repo: '{{ item.script_source }}'
    dest: /{{ ansible_user }}/temp/{{ item.name }}
    version: main
    update: yes
  with_items: "{{ apps }}"
  when: item.script_source is regex('^http.*')

# - name: Copy shutdown and startup scripts to destination directory
#   copy:
#     src: "{{ item.src }}"
#     dest: "{{ item.dest }}"
#     remote_src: yes
#   loop:
#     - src: /{{ ansible_user }}/temp/scripts/{{ appname }}_shutdown.sh
#       dest: /{{ ansible_user }}/company/{{ domain1 }}/{{ appname }}
#     - src: /{{ ansible_user }}/temp/scripts/{{ appname }}_startup.sh
#       dest: /{{ ansible_user }}/company/{{ domain2 }}/{{ appname }}

# - name: Set executable permissions for multiple files
#   file:
#     path: "{{ item }}"
#     mode: '0755'
#   loop:
#     - /{{ ansible_user }}/company/{{ domain1 }}/{{ appname }}_shutdown.sh
#     - /{{ ansible_user }}/company/{{ domain2 }}/{{ appname }}_startup.sh
